name: issue echo
on: [push, issues]
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo event name
              run: echo "${{ toJson(github.event_name) }}"
            - name: echo event detail
              run: echo "${{ toJson(github.event) }}"